### IMPORTAR LIBRERIAS

In [1]:
import pandas as pd

### Carga de archivo csv

In [4]:
data_csv= pd.read_csv('Desktop/ventas.csv', encoding= "ISO-8859-1")

In [5]:
data_csv.head()

,ï»¿ID_Venta,Fecha,Producto,Categoria,Cantidad,Precio_Unitario,Medio_Pago
0,1,2026-08-01,Notebook,TecnologÃ­a,2,850000,Efectivo
1,2,2026-08-02,Mouse,Accesorios,5,18000,Transferencia
2,3,2026-08-03,Teclado,Accesorios,3,32000,Tarjeta
3,4,2026-08-04,Monitor,TecnologÃ­a,2,250000,Transferencia
4,5,2026-08-05,Auriculares,Accesorios,4,45000,Tarjeta

### Carga de archivo Json

In [7]:
data_json= pd.read_json('Desktop/clientes.json')

In [8]:
total_clientes = len(data_json)
print(f"Total de clientes: {total_clientes}")

Total de clientes: 20

### Carga de archivo Excel

In [9]:
data_excel = pd.read_excel('Desktop/inventario.xlsx', sheet_name='Inventario')

In [10]:
data_excel.head()

,ID Producto,Nombre del Producto,Categoría,Precio Unitario ($),Stock Actual,Stock Mínimo,Valor Total Stock ($),Estado de Stock,Ubicación Almacén,Última Reposición
0,PROD-101,"Monitor LED 27"" 4K",Tecnología,350.0,25,10,8750,Óptimo,Pasillo A-1,2026-08-15
1,PROD-102,Teclado Mecánico RGB,Tecnología,75.0,8,15,600,Reordenar,Pasillo A-2,2026-07-10
2,PROD-103,Silla Ergonómica Oficina,Oficina,220.0,12,5,2640,Óptimo,Pasillo B-1,2026-08-01
3,PROD-104,Escritorio Ajustable,Oficina,450.0,4,5,1800,Reordenar,Pasillo B-2,2026-06-20
4,PROD-105,Impresora Multifunción,Tecnología,280.0,15,8,4200,Óptimo,Pasillo A-3,2026-08-22

In [13]:
# Excluir la fila final de totales
df_productos = data_excel[data_excel['ID Producto'] != 'TOTALES / PROMEDIOS'].dropna(subset=['ID Producto'])

# Calcular el promedio de la columna 'Stock Actual'
promedio_stock = df_productos['Stock Actual'].mean()

print(f"El promedio de stock disponible es: {promedio_stock:.2f} unidades")

El promedio de stock disponible es: 43.05 unidades

### IMPORTACION DE MATPLOTLIB

In [14]:
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.